### ISSUE TITLE
运行示例代码，打印出来的是乱码（如下）

### ISSUE THREAD

**Issue by zjgnlzq** [ipipdotnet/datx-nodejs#1]
[ '\u0002\u001f��\u0000\u0000\u0015�\u0002?�~\u0001\u0000\u000f�\u0002�7\u0006\u0000\u000f�\u0002���\u0017\u0000\u001b�\u0002��i\u0000\u0000\u000f�\u0003���\u0000\u0000\u000f�\u0004?�9\u0004\u0000\u0015�\u0004O�p\u0017\u0000\u0015�\u0004W�?\u0000\u0000\u001b�\u0004_�~\u0001\u0000\u000f�\u0004�9\u0004\u0000\u0015�\u0004��x\u0000\u0000\u000f�\u0004��i\u0000\u0000\u000f�\u0004���\u0003\u0000\u0015�\u0004���\u0000\u0000\u000f�\u0004���\u0003\u0000\u0015�\u0004��i\u0000\u0000\u000f�\u0004���\u0003\u0000\u0015�\u0004��i\u0000\u0000\u000f�\u0004��[\u0017\u0000\u0015�\u0004��~\u0001\u0000\u000f�\u0004��?\u0000\u0000\u001b�\u0004��i\u0000\u0000\u000f�\u0005\u0000\u0002�\u0000\u0000\u000f�\u0005\u0000\u0004�\n\u0000\u0015�\u0005\u0000',
  '�\u0000\u0000\u000f�\u0005\u0000\n�\n\u0000\u0015�\u0005\u0000\u000b�\u0000\u0000\u000f�\u0005\u0000\u000e�\n\u0000\u0015�\u0005\u0000\u0010�\u0000\u0000\u000f�\u0005\u0000\u0011�\n\u0000\u0015�\u0005\u0000\u001c�\u0000\u0000\u000f�\u0005\u0000\u001d�\n\u0000\u0015�\u0005\u0000,�\u0000\u0000\u000f�\u0005\u0000-�\u0000\u0000\u0015�\u0005\u00004�\u0000\u0000\u000f�\u0005\u00005�\n\u0000\u0015�\u0005\u0000;�\u0000\u0000\u000f�\u0005\u0000>�\u0001\u0000\u0015�\u0005\u0000C�\u0000\u0000\u000f�\u0005\u0000F�\n\u0000\u0015�\u0005\u0000H�\u0000\u0000\u000f�\u0005\u0000J�\u0001\u0000\u0015�\u0005\u0000[�\u0000\u0000\u000f�\u0005\u0000^�\n\u0000\u0015�\u0005\u0000a�\u0000\u0000\u000f�\u0005\u0000f�\n\u0000\u0015�\u0005\u0000p�\u0000\u0000\u000f�\u0005\u0000r�\n\u0000\u0015�\u0005\u0000u�\u0000\u0000\u000f�\u0005\u0000v�\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000��\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000��\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000��\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000��\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000��\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000��\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000��\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000��\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000��\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000��\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000Ι\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000љ\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000֙\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000ޙ\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000�\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000�\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000�\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000��\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0000��\n\u0000\u0015�\u0005\u0000��\u0000\u0000\u000f�\u0005\u0001\u0013�\u0001\u0000\u0015�\u0005\u0001\u0014�\n\u0000\u0015�\u0005\u0001��\u0001\u0000\u0015�\u0005\u0002\b�\u0000\u0000\u000f�\u0005\u0002\n�\u0001\u0000\u0015�\u0005\u0002\u0014�\u0000\u0000\u000f�\u0005\u0002\u0016�\u0001\u0000\u0015�\u0005\u0002\u001c�\u0000\u0000\u000f�\u0005\u0002\u001d�\u0000\u0000\u0015�\u0005\u0002 �\u0000\u0000\u000f�\u0005\u0002!�\u0001\u0000\u0015�\u0005\u0002%�\u0000\u0000\u000f�\u0005\u0002&�\u0001\u0000\u0015�\u0005\u0002(�\u0000\u0000\u000f�\u0005\u0002)�\u0000\u0000\u0015�\u0005\u0002-�\u0000\u0000\u000f�\u0005\u0002.�\u0000\u0000\u0015�\u0005\u0002/�\u0000\u0000\u000f�\u0005\u00027�\u0000\u0000\u0015�\u0005\u0002?�\u0000\u0000\u000f�\u0005\u0002_�\u0000\u0000\u0015�\u0005\u0002m�\u0000\u0000\u000f�\u0005\u0002n�\n\u0000\u0015�\u0005\u0002��\u0000\u0000\u000f�\u0005\u0002��\n\u0000\u0015�\u0005\u0002��\u0000\u0000\u000f�\u0005\u0002ҙ\n\u0000\u0015�\u0005\u0002��\u0000\u0000\u000f�\u0005\u0002�\n\u0000\u0015�\u0005\u0002��\u0000\u0000\u000f�\u0005\u0003��\u0001\u0000\u0015�\u0005\u0004��\u0000\u0000\u000f�\u0005\u0005��\n\u0000\u0015�\u0005\u0007\u0000�\u0000\u0000\u000f�\u0005\u0007\u0002�\u0001\u0000\u0015�\u0005\u0007\u0010�\u0000\u0000\u000f�\u0005\u0007\u0011�\u0000\u0000\u0015�\u0005\u0007@�\u0000\u0000\u000f�\u0005\u0007B�\u0000\u0000\u0015�\u0005\u0007��\u0000\u0000\u000f�\u0005\u0007��\n\u0000\u0015�\u0005\u0007��\u0000\u0000\u000f�\u0005\u0007�\n\u0000\u0015�\u0005\u0007��\u0000\u0000\u000f�\u0005\f��\u0001\u0000\u0015�\u0005\u000e��\n\u0000\u0015�\u0005\u0010��\u0001\u0000\u0015�\u0005\u0011��\u0000\u0000\u0015�\u0005\u0016��\u0001\u0000\u0015�\u0005\u0017��\u0000\u0000\u000f�\u0005\u0018��\u0001\u0000\u0015�\u0005\u0019��\u0000\u0000\u0015�\u0005\u001a��\u0000\u0000\u000f�\u0005\u001d\u000f�\u0001\u0000\u0015�\u0005\u001d\u0013�\u0000\u0000\u0015�\u0005\u001d/�\u0001\u0000\u0015�\u0005\u001d7�\u0000\u0000\u0015�\u0005\u001f��\u0001\u0000\u0015�\u0005\'�?\u0000\u0000\u001b�\u0005/�-\u0001\u0000\u001b�\u00057�[\u0017\u0000\u0015�\u00058\u0003�\u0000\u0000\u0015�\u00058\u0007�\u0001\u0000\u0015�\u00058\u000b�\n\u0000\u0015�\u00058\f�\u0000\u0000\u000f�\u00058\r�\u0000\u0000\u000f�\u00058\u000f�\u0000\u0000\u000f�\u00058\u0017�\u0000\u0000\u000f�\u00058_�\u0000\u0000\u000f�\u0005:��\u0000\u0000\u000f�\u0005;��\f\u0000\u0015�\u0005<�\u001d,\u0000\u001b�\u0005?��\u0000\u0000\u000f�\u0005�9\u0004\u0000\u0015�\u0005��~\u001f\u0000\u000f�\u0005��!\u001f\u0000\u0015�\u0005��~\u001f\u0000\u000f�\u0005��L\u001e\u0000\u0015�\u0005��~\u001f\u0000\u000f�\u0005���\u0001\u0000\u0015�\u0005���\u0000\u0000\u000f�\u0005��?\u0000\u0000\u001b�\u0006���\u0000\u0000\u000f�\u0007\u001f�\u0018!\u0000\u000f�\u0007/�[\u0017\u0000\u0015�\u00077�?\u0000\u0000\u001b�\u0007?��\u0000\u0000\u000f�\u0007_��\u0000\u0000\u000f�\u0007���\u0018\u0000\u001b�\u0007��?\u0000\u0000\u001b�\u0007���\u0018\u0000\u001b�\u000b��?\u0000\u0000\u001b�\f1��\u0000\u0000\u0015�\f2��\u0001\u0000\u0015�\r?��\u0000\u0000\u0015�\r��\u0001\u0000\u0015�\r���\u0000\u0000\u000f�\r���"\u0000\u001

**Comment by zjgnlzq** [comment]
@ilsanbao @ipipdotnet

**Comment by ilsanbao** [comment]
@zjgnlzq 你的库哪里下载的

**Comment by zjgnlzq** [comment]
https://www.ipip.net/free_download/  @ilsanbao 这个地址下载的
