### ISSUE TITLE
部分ip地址无法解析

### ISSUE THREAD

**Issue by Goofo** [ipipdotnet/datx-nodejs#2]
数据源是2017年7月的付费下载,之前使用php解析, 现在要使用nodejs解析,但是发现 有ip地址无法正确输出结果(官网查询和php环境都能正常查询)
/// 这个文件是直接copy的 datx-nodejs/lib/district.js
/// copy源码 只是方便调试修改,逻辑未变动
const geo = require("./src/geoip");
// 这里的quxian.datx 是数据源
const d = new geo(path.join(__dirname, 'quxian.datx'));
/// 这个是测试我的本机ip地址 返回null
console.log(d.findSync('219.142.86.76'));
/// 这个是demo中的测试地址 能正常返回 [ '中国', '北京', '北京', '朝阳区', '110105', '3.1', '116.48548', '39.9484' ]
console.log(d.findSync('123.121.17.72'));

**Comment by Goofo** [comment]
//这里是使用npm源安装的包
const ipip = require('ipip-datx');
const d = new ipip.District(path.join(__dirname, 'quxian.datx'));
console.log(d.findSync('219.142.86.76'));
console.log(d.findSync('123.121.17.72'));

/// 输出
null
[ '中国', '北京', '北京', '朝阳区', '110105', '3.1', '116.48548', '39.9484' ]

**Comment by ipipdotnet** [comment]
已经修复
